## Start a development stack with the current repo mounted into ros_ws/src/

services:
  arena_camera:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    image: ghcr.io/apl-ocean-engineering/arena_camera_ros:${IMAGE_TAG:-latest}
    stdin_open: true
    tty: true
    network_mode: host

  # Prebuild includes rosdep and vcs import
  # (basically, everything before "catkin build")
  prebuild:
    extends: arena_camera
    # Local-only image
    image: arena_camera_ros:prebuild
    build:
      target: prebuild
    command: /bin/bash

  # Prebuild with _this_ copy of the repo mounted
  #
  mount_local:
    extends: prebuild
    volumes:
      - type: bind
        source: ..
        target: /home/ros/ros_ws/src/arena_camera_ros

  build_local:
    extends: arena_camera
    build:
      args:
        BUILD_TYPE: local
